name: SDK publish

on:
  push:
    branches:
      - 'feature/ci_update'
    tags-ignore:
      - '**'

jobs:
  unit:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install bundler dependencies
      run: bundle install
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
      env:
        CI: true

  publish:
    needs: [unit]
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install bundler dependencies
      run: bundle install
    - name: Run build
      run: bundle exec fastlane buildLane
      env:
        CI: true
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
